# Generated by Django 5.1 on 2025-07-17 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en curso', 'En Curso'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20)),
                ('categoria', models.CharField(choices=[('equipo', 'Equipo'), ('impresora', 'Impresora'), ('mantenimiento', 'Mantenimiento'), ('ofimatica', 'Ofimatica'), ('internet', 'Internet'), ('programas', 'Programas'), ('telefono', 'Telefono')], max_length=30)),
                ('tiempo_resolucion_seg', models.PositiveIntegerField(blank=True, null=True)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
                ('fecha_inicio_proceso', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_atendidos', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['estado'], name='ticket_tick_estado_924ada_idx'), models.Index(fields=['empleado'], name='ticket_tick_emplead_6c0c00_idx'), models.Index(fields=['fecha_creado'], name='ticket_tick_fecha_c_b8fab9_idx'), models.Index(fields=['categoria'], name='ticket_tick_categor_c6cbcc_idx')],
            },
        ),
    ]
